// ============================================
// Kurumsal Tema - Ana Tema Dosyası
// Profesyonel işletmeler için - TR/EN destekli
// ============================================

import type { ThemeData } from '@/types/theme';
import { homePage } from './pages/home';
import { aboutPage } from './pages/about';
import { servicesPage } from './pages/services';
import { portfolioPage } from './pages/portfolio';
import { contactPage } from './pages/contact';
import { kurumsalHeader } from './header';
import { kurumsalFooter } from './footer';

// Çeviriler
const translations = {
  tr: {
    siteName: 'Kurumsal',
    siteSlogan: 'Profesyonel İş Çözümleri',
    // Navbar
    nav: {
      home: 'Ana Sayfa',
      services: 'Hizmetler',
      portfolio: 'Referanslar',
      about: 'Hakkımızda',
      contact: 'İletişim',
      getQuote: 'Teklif Al',
      consulting: 'Danışmanlık',
      technology: 'Teknoloji',
      training: 'Eğitim',
      research: 'Araştırma',
    },
    // Hero
    heroTitle: 'İşinizi Büyütmenin Akıllı Yolu',
    heroSubtitle: 'Stratejik danışmanlık ve teknoloji çözümleriyle işletmenizi dönüştürün.',
    heroCta: 'Ücretsiz Danışmanlık',
    heroCtaSecondary: 'Hizmetlerimiz',
    // Hizmetler
    servicesTitle: 'Hizmetlerimiz',
    servicesSubtitle: 'İşletmenizin ihtiyaçlarına özel çözümler',
    servicesPageTitle: 'Hizmetlerimiz',
    serviceConsulting: 'Stratejik Danışmanlık',
    serviceConsultingDesc: 'İş stratejinizi geliştirmek için uzman danışmanlık hizmetleri.',
    serviceTechnology: 'Dijital Dönüşüm',
    serviceTechnologyDesc: 'İşletmenizi dijital çağa taşıyacak teknoloji çözümleri.',
    serviceTraining: 'Kurumsal Eğitim',
    serviceTrainingDesc: 'Ekibinizi güçlendiren profesyonel eğitim programları.',
    serviceResearch: 'Pazar Araştırması',
    serviceResearchDesc: 'Veriye dayalı kararlar için kapsamlı pazar analizleri.',
    learnMore: 'Detaylar',
    requestService: 'Hizmet Talep Et',
    // Hakkımızda
    aboutTitle: 'Neden Biz?',
    aboutText: '15 yılı aşkın tecrübemizle 500\'den fazla projeyi başarıyla tamamladık.',
    aboutPageTitle: 'Hakkımızda',
    ourMission: 'Misyonumuz',
    ourVision: 'Vizyonumuz',
    ourValues: 'Değerlerimiz',
    ourTeam: 'Ekibimiz',
    leadership: 'Yönetim',
    // İstatistikler
    statsProjects: 'Tamamlanan Proje',
    statsClients: 'Mutlu Müşteri',
    statsYears: 'Yıllık Tecrübe',
    statsAwards: 'Ödül',
    // Referanslar
    portfolioTitle: 'Referanslarımız',
    portfolioSubtitle: 'Başarı hikayelerimiz',
    portfolioPageTitle: 'Referanslar',
    viewCaseStudy: 'Vaka Çalışması',
    allProjects: 'Tüm Projeler',
    clientTestimonials: 'Müşteri Görüşleri',
    // CTA
    ctaTitle: 'Birlikte Çalışalım',
    ctaSubtitle: 'İşletmenizi dönüştürmek için ilk adımı atın',
    ctaButton: 'İletişime Geçin',
    // İletişim
    contactPageTitle: 'İletişim',
    contactName: 'Adınız Soyadınız',
    contactEmail: 'E-posta Adresiniz',
    contactPhone: 'Telefon',
    contactCompany: 'Şirket Adı',
    contactSubject: 'Konu',
    contactMessage: 'Mesajınız',
    contactSubmit: 'Gönder',
    contactInfo: 'İletişim Bilgileri',
    officeHours: 'Çalışma Saatleri',
    weekdays: 'Pazartesi - Cuma: 09:00 - 18:00',
    weekend: 'Cumartesi - Pazar: Kapalı',
    // Footer
    footer: {
      description: 'Stratejik danışmanlık ve teknoloji çözümleriyle işletmenizi dönüştürün.',
      quickLinks: 'Hızlı Linkler',
      services: 'Hizmetler',
      company: 'Şirket',
      support: 'Destek',
      home: 'Ana Sayfa',
      about: 'Hakkımızda',
      contact: 'İletişim',
      newsletter: 'Bülten',
      newsletterText: 'İş dünyasından haberler ve güncellemeler için abone olun.',
      subscribe: 'Abone Ol',
      copyright: '© 2026 Kurumsal. Tüm hakları saklıdır.',
      privacyPolicy: 'Gizlilik Politikası',
      termsOfUse: 'Kullanım Şartları',
    },
  },
  en: {
    siteName: 'Corporate',
    siteSlogan: 'Professional Business Solutions',
    // Navbar
    nav: {
      home: 'Home',
      services: 'Services',
      portfolio: 'Portfolio',
      about: 'About Us',
      contact: 'Contact',
      getQuote: 'Get Quote',
      consulting: 'Consulting',
      technology: 'Technology',
      training: 'Training',
      research: 'Research',
    },
    // Hero
    heroTitle: 'The Smart Way to Grow Your Business',
    heroSubtitle: 'Transform your business with strategic consulting and technology solutions.',
    heroCta: 'Free Consultation',
    heroCtaSecondary: 'Our Services',
    // Services
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Custom solutions for your business needs',
    servicesPageTitle: 'Our Services',
    serviceConsulting: 'Strategic Consulting',
    serviceConsultingDesc: 'Expert consulting services to develop your business strategy.',
    serviceTechnology: 'Digital Transformation',
    serviceTechnologyDesc: 'Technology solutions to bring your business into the digital age.',
    serviceTraining: 'Corporate Training',
    serviceTrainingDesc: 'Professional training programs that empower your team.',
    serviceResearch: 'Market Research',
    serviceResearchDesc: 'Comprehensive market analysis for data-driven decisions.',
    learnMore: 'Learn More',
    requestService: 'Request Service',
    // About
    aboutTitle: 'Why Us?',
    aboutText: 'With over 15 years of experience, we have successfully completed more than 500 projects.',
    aboutPageTitle: 'About Us',
    ourMission: 'Our Mission',
    ourVision: 'Our Vision',
    ourValues: 'Our Values',
    ourTeam: 'Our Team',
    leadership: 'Leadership',
    // Stats
    statsProjects: 'Completed Projects',
    statsClients: 'Happy Clients',
    statsYears: 'Years of Experience',
    statsAwards: 'Awards',
    // Portfolio
    portfolioTitle: 'Our Portfolio',
    portfolioSubtitle: 'Our success stories',
    portfolioPageTitle: 'Portfolio',
    viewCaseStudy: 'View Case Study',
    allProjects: 'All Projects',
    clientTestimonials: 'Client Testimonials',
    // CTA
    ctaTitle: 'Let\'s Work Together',
    ctaSubtitle: 'Take the first step to transform your business',
    ctaButton: 'Contact Us',
    // Contact
    contactPageTitle: 'Contact',
    contactName: 'Full Name',
    contactEmail: 'Email Address',
    contactPhone: 'Phone',
    contactCompany: 'Company Name',
    contactSubject: 'Subject',
    contactMessage: 'Your Message',
    contactSubmit: 'Submit',
    contactInfo: 'Contact Information',
    officeHours: 'Office Hours',
    weekdays: 'Monday - Friday: 9:00 AM - 6:00 PM',
    weekend: 'Saturday - Sunday: Closed',
    // Footer
    footer: {
      description: 'Transform your business with strategic consulting and technology solutions.',
      quickLinks: 'Quick Links',
      services: 'Services',
      company: 'Company',
      support: 'Support',
      home: 'Home',
      about: 'About Us',
      contact: 'Contact',
      newsletter: 'Newsletter',
      newsletterText: 'Subscribe for business news and updates.',
      subscribe: 'Subscribe',
      copyright: '© 2026 Corporate. All rights reserved.',
      privacyPolicy: 'Privacy Policy',
      termsOfUse: 'Terms of Use',
    },
  },
  de: {
    siteName: 'Unternehmen',
    siteSlogan: 'Professionelle Geschäftslösungen',
    // Navbar
    nav: {
      home: 'Startseite',
      services: 'Dienstleistungen',
      portfolio: 'Referenzen',
      about: 'Über uns',
      contact: 'Kontakt',
      getQuote: 'Angebot anfordern',
      consulting: 'Beratung',
      technology: 'Technologie',
      training: 'Schulung',
      research: 'Forschung',
    },
    // Hero
    heroTitle: 'Der kluge Weg, Ihr Unternehmen zu wachsen',
    heroSubtitle: 'Transformieren Sie Ihr Unternehmen mit strategischer Beratung und Technologielösungen.',
    heroCta: 'Kostenlose Beratung',
    heroCtaSecondary: 'Unsere Dienstleistungen',
    // Dienstleistungen
    servicesTitle: 'Unsere Dienstleistungen',
    servicesSubtitle: 'Maßgeschneiderte Lösungen für Ihre Geschäftsanforderungen',
    servicesPageTitle: 'Unsere Dienstleistungen',
    serviceConsulting: 'Strategische Beratung',
    serviceConsultingDesc: 'Expertenberatung zur Entwicklung Ihrer Geschäftsstrategie.',
    serviceTechnology: 'Digitale Transformation',
    serviceTechnologyDesc: 'Technologielösungen, um Ihr Unternehmen ins digitale Zeitalter zu bringen.',
    serviceTraining: 'Unternehmensschulung',
    serviceTrainingDesc: 'Professionelle Schulungsprogramme, die Ihr Team stärken.',
    serviceResearch: 'Marktforschung',
    serviceResearchDesc: 'Umfassende Marktanalyse für datengestützte Entscheidungen.',
    learnMore: 'Mehr erfahren',
    requestService: 'Service anfordern',
    // Über uns
    aboutTitle: 'Warum wir?',
    aboutText: 'Mit über 15 Jahren Erfahrung haben wir erfolgreich mehr als 500 Projekte abgeschlossen.',
    aboutPageTitle: 'Über uns',
    ourMission: 'Unsere Mission',
    ourVision: 'Unsere Vision',
    ourValues: 'Unsere Werte',
    ourTeam: 'Unser Team',
    leadership: 'Führung',
    // Statistiken
    statsProjects: 'Abgeschlossene Projekte',
    statsClients: 'Zufriedene Kunden',
    statsYears: 'Jahre Erfahrung',
    statsAwards: 'Auszeichnungen',
    // Referenzen
    portfolioTitle: 'Unsere Referenzen',
    portfolioSubtitle: 'Unsere Erfolgsgeschichten',
    portfolioPageTitle: 'Referenzen',
    viewCaseStudy: 'Fallstudie ansehen',
    allProjects: 'Alle Projekte',
    clientTestimonials: 'Kundenmeinungen',
    // CTA
    ctaTitle: 'Lass uns zusammenarbeiten',
    ctaSubtitle: 'Machen Sie den ersten Schritt zur Transformation Ihres Unternehmens',
    ctaButton: 'Kontaktieren Sie uns',
    // Kontakt
    contactPageTitle: 'Kontakt',
    contactName: 'Vollständiger Name',
    contactEmail: 'E-Mail-Adresse',
    contactPhone: 'Telefon',
    contactCompany: 'Firmenname',
    contactSubject: 'Betreff',
    contactMessage: 'Ihre Nachricht',
    contactSubmit: 'Absenden',
    contactInfo: 'Kontaktinformationen',
    officeHours: 'Öffnungszeiten',
    weekdays: 'Montag - Freitag: 09:00 - 18:00',
    weekend: 'Samstag - Sonntag: Geschlossen',
    // Footer
    footer: {
      description: 'Transformieren Sie Ihr Unternehmen mit strategischer Beratung und Technologielösungen.',
      quickLinks: 'Schnelllinks',
      services: 'Dienstleistungen',
      company: 'Unternehmen',
      support: 'Support',
      home: 'Startseite',
      about: 'Über uns',
      contact: 'Kontakt',
      newsletter: 'Newsletter',
      newsletterText: 'Abonnieren Sie Business-News und Updates.',
      subscribe: 'Abonnieren',
      copyright: '© 2026 Unternehmen. Alle Rechte vorbehalten.',
      privacyPolicy: 'Datenschutz',
      termsOfUse: 'Nutzungsbedingungen',
    },
  },
  fr: {
    siteName: 'Entreprise',
    siteSlogan: 'Solutions d\'affaires professionnelles',
    // Navbar
    nav: {
      home: 'Accueil',
      services: 'Services',
      portfolio: 'Références',
      about: 'À propos',
      contact: 'Contact',
      getQuote: 'Demander un devis',
      consulting: 'Conseil',
      technology: 'Technologie',
      training: 'Formation',
      research: 'Recherche',
    },
    // Hero
    heroTitle: 'La façon intelligente de développer votre entreprise',
    heroSubtitle: 'Transformez votre entreprise avec des solutions de conseil stratégique et de technologie.',
    heroCta: 'Consultation gratuite',
    heroCtaSecondary: 'Nos services',
    // Services
    servicesTitle: 'Nos services',
    servicesSubtitle: 'Solutions personnalisées pour vos besoins d\'entreprise',
    servicesPageTitle: 'Nos services',
    serviceConsulting: 'Conseil stratégique',
    serviceConsultingDesc: 'Services de conseil d\'experts pour développer votre stratégie d\'entreprise.',
    serviceTechnology: 'Transformation digitale',
    serviceTechnologyDesc: 'Solutions technologiques pour amener votre entreprise à l\'ère numérique.',
    serviceTraining: 'Formation d\'entreprise',
    serviceTrainingDesc: 'Programmes de formation professionnels qui renforcent votre équipe.',
    serviceResearch: 'Étude de marché',
    serviceResearchDesc: 'Analyse de marché complète pour des décisions basées sur les données.',
    learnMore: 'En savoir plus',
    requestService: 'Demander un service',
    // À propos
    aboutTitle: 'Pourquoi nous ?',
    aboutText: 'Avec plus de 15 ans d\'expérience, nous avons réalisé avec succès plus de 500 projets.',
    aboutPageTitle: 'À propos de nous',
    ourMission: 'Notre mission',
    ourVision: 'Notre vision',
    ourValues: 'Nos valeurs',
    ourTeam: 'Notre équipe',
    leadership: 'Direction',
    // Statistiques
    statsProjects: 'Projets réalisés',
    statsClients: 'Clients satisfaits',
    statsYears: 'Années d\'expérience',
    statsAwards: 'Prix',
    // Références
    portfolioTitle: 'Nos références',
    portfolioSubtitle: 'Nos histoires de succès',
    portfolioPageTitle: 'Références',
    viewCaseStudy: 'Voir l\'étude de cas',
    allProjects: 'Tous les projets',
    clientTestimonials: 'Témoignages clients',
    // CTA
    ctaTitle: 'Travaillons ensemble',
    ctaSubtitle: 'Faites le premier pas pour transformer votre entreprise',
    ctaButton: 'Contactez-nous',
    // Contact
    contactPageTitle: 'Contact',
    contactName: 'Nom complet',
    contactEmail: 'Adresse e-mail',
    contactPhone: 'Téléphone',
    contactCompany: 'Nom de l\'entreprise',
    contactSubject: 'Sujet',
    contactMessage: 'Votre message',
    contactSubmit: 'Envoyer',
    contactInfo: 'Coordonnées',
    officeHours: 'Heures d\'ouverture',
    weekdays: 'Lundi - Vendredi: 9h00 - 18h00',
    weekend: 'Samedi - Dimanche: Fermé',
    // Footer
    footer: {
      description: 'Transformez votre entreprise avec des solutions de conseil stratégique et de technologie.',
      quickLinks: 'Liens rapides',
      services: 'Services',
      company: 'Entreprise',
      support: 'Support',
      home: 'Accueil',
      about: 'À propos',
      contact: 'Contact',
      newsletter: 'Newsletter',
      newsletterText: 'Abonnez-vous pour les actualités et mises à jour d\'affaires.',
      subscribe: 'S\'abonner',
      copyright: '© 2026 Entreprise. Tous droits réservés.',
      privacyPolicy: 'Politique de confidentialité',
      termsOfUse: 'Conditions d\'utilisation',
    },
  },
};

export const corporateTheme: ThemeData = {
  metadata: {
    id: 'theme-kurumsal',
    name: 'Kurumsal İşletme',
    description: 'Profesyonel işletmeler için modern kurumsal tema - TR/EN destekli',
    version: '2.0.0',
    thumbnail: '/themes/corporate.png',
    author: 'Page Builder',
    category: 'corporate',
    pages: [
      { slug: 'home', title: 'Ana Sayfa', file: 'pages/home.json' },
      { slug: 'about', title: 'Hakkımızda', file: 'pages/about.json' },
      { slug: 'services', title: 'Hizmetler', file: 'pages/services.json' },
      { slug: 'portfolio', title: 'Referanslar', file: 'pages/portfolio.json' },
      { slug: 'contact', title: 'İletişim', file: 'pages/contact.json' },
    ],
    settings: {
      primaryColor: '#2563eb',
      secondaryColor: '#64748b',
      accentColor: '#0ea5e9',
      fontFamily: "'Inter', sans-serif",
      defaultLanguage: 'tr',
      translations: translations,
      header: kurumsalHeader,
      footer: kurumsalFooter,
      company: {
        name: 'Kurumsal',
        slogan: 'Profesyonel İş Çözümleri',
        logo: '/themes/corporate/logo.svg',
      },
      contact: {
        email: 'info@kurumsal.com',
        phone: '+90 312 456 7890',
        address: 'Çankaya, Kızılay Cad. No: 45, Ankara, Türkiye',
        mapUrl: 'https://maps.google.com/?q=39.9208,32.8541',
      },
      social: {
        facebook: 'https://facebook.com/kurumsal',
        instagram: 'https://instagram.com/kurumsal',
        twitter: 'https://twitter.com/kurumsal',
        linkedin: 'https://linkedin.com/company/kurumsal',
        youtube: '',
      },
      seo: {
        metaTitle: 'Kurumsal | Profesyonel İş Çözümleri',
        metaDescription: 'Stratejik danışmanlık, dijital dönüşüm ve kurumsal eğitim hizmetleri. 15 yılı aşkın tecrübe ile yanınızdayız.',
        metaKeywords: 'kurumsal, danışmanlık, strateji, dijital dönüşüm, eğitim',
        googleAnalyticsId: '',
      },
      animations: {
        enabled: true,
        defaultType: 'fadeIn',
        defaultDuration: 500,
        staggerDelay: 80,
      },
    },
  },
  pages: {
    home: homePage,
    about: aboutPage,
    services: servicesPage,
    portfolio: portfolioPage,
    contact: contactPage,
  },
};

// Export alias
export { corporateTheme as kurumsalTheme };
