// ============================================
// E-Ticaret Teması - Ana Tema Dosyası
// Online mağaza ve e-ticaret siteleri için - TR/EN destekli
// ============================================

import type { ThemeData } from '@/types/theme';
import { eticaretHeader } from './header';
import { eticaretFooter } from './footer';
import { homePage } from './pages/home';
import { aboutPage } from './pages/about';
import { contactPage } from './pages/contact';
import { shopPage } from './pages/shop';
import { womenPage } from './pages/women';
import { menPage } from './pages/men';
import { kidsPage } from './pages/kids';
import { accessoriesPage } from './pages/accessories';

const translations = {
    tr: {
        siteName: 'ShopStyle',
        siteSlogan: 'Tarzını Keşfet',
        // Navbar
        nav: {
            home: 'Ana Sayfa',
            shop: 'Mağaza',
            categories: 'Kategoriler',
            about: 'Hakkımızda',
            contact: 'İletişim',
            cart: 'Sepet',
            wishlist: 'Favoriler',
            account: 'Hesabım',
            women: 'Kadın',
            men: 'Erkek',
            kids: 'Çocuk',
            accessories: 'Aksesuarlar',
            sale: 'İndirimler',
        },
        // Hero
        heroTitle: 'Yeni Sezon Koleksiyonu',
        heroSubtitle: '%50\'ye varan indirimler! Tarzınızı yansıtan parçalar için alışverişe başlayın.',
        heroCta: 'Alışverişe Başla',
        heroCtaSecondary: 'Koleksiyonlar',
        // Mağaza
        shopTitle: 'Mağaza',
        shopSubtitle: 'Tüm ürünleri keşfedin',
        filterBy: 'Filtrele',
        sortBy: 'Sırala',
        priceRange: 'Fiyat Aralığı',
        color: 'Renk',
        size: 'Beden',
        addToCart: 'Sepete Ekle',
        addToWishlist: 'Favorilere Ekle',
        outOfStock: 'Stokta Yok',
        inStock: 'Stokta Var',
        // Kategoriler
        categoriesTitle: 'Kategoriler',
        categoryWomen: 'Kadın',
        categoryMen: 'Erkek',
        categoryKids: 'Çocuk',
        categoryAccessories: 'Aksesuarlar',
        // Öne Çıkanlar
        newArrivalsTitle: 'Yeni Gelenler',
        bestSellersTitle: 'Çok Satanlar',
        saleTitle: 'İndirimler',
        featuredProducts: 'Öne Çıkan Ürünler',
        viewAll: 'Tümünü Görüntüle',
        // Hakkımızda
        aboutTitle: 'Hakkımızda',
        aboutText: '2018 yılından bu yana moda tutkusuyla sizlere hizmet veriyoruz.',
        aboutPageTitle: 'Hakkımızda',
        ourStory: 'Hikayemiz',
        ourMission: 'Misyonumuz',
        ourVision: 'Vizyonumuz',
        // İletişim
        contactTitle: 'İletişim',
        contactPageTitle: 'İletişim',
        contactName: 'Ad Soyad',
        contactEmail: 'E-posta',
        contactPhone: 'Telefon',
        contactMessage: 'Mesajınız',
        contactSubmit: 'Gönder',
        contactAddress: 'Adres',
        // Sepet
        cartTitle: 'Sepet',
        cartEmpty: 'Sepetiniz boş',
        cartSubtotal: 'Ara Toplam',
        cartShipping: 'Kargo',
        cartTotal: 'Toplam',
        cartCheckout: 'Ödemeye Geç',
        continueShopping: 'Alışverişe Devam Et',
        // Favoriler
        wishlistTitle: 'Favoriler',
        wishlistEmpty: 'Favorileriniz boş',
        // Hesap
        accountTitle: 'Hesabım',
        ordersTitle: 'Siparişlerim',
        orderHistory: 'Sipariş Geçmişi',
        accountDetails: 'Hesap Bilgileri',
        addresses: 'Adreslerim',
        logout: 'Çıkış Yap',
        // Footer
        footer: {
            description: 'Moda tutkusuyla sizlere hizmet veriyoruz.',
            quickLinks: 'Hızlı Linkler',
            customerService: 'Müşteri Hizmetleri',
            contact: 'İletişim',
            home: 'Ana Sayfa',
            shop: 'Mağaza',
            about: 'Hakkımızda',
            faq: 'SSS',
            shipping: 'Kargo Bilgileri',
            returns: 'İade ve Değişim',
            sizeGuide: 'Beden Rehberi',
            copyright: '© 2026 ShopStyle. Tüm hakları saklıdır.',
            privacyPolicy: 'Gizlilik Politikası',
            termsOfUse: 'Kullanım Şartları',
            paymentMethods: 'Ödeme Yöntemleri',
        },
    },
    en: {
        siteName: 'ShopStyle',
        siteSlogan: 'Discover Your Style',
        // Navbar
        nav: {
            home: 'Home',
            shop: 'Shop',
            categories: 'Categories',
            about: 'About',
            contact: 'Contact',
            cart: 'Cart',
            wishlist: 'Wishlist',
            account: 'Account',
            women: 'Women',
            men: 'Men',
            kids: 'Kids',
            accessories: 'Accessories',
            sale: 'Sale',
        },
        // Hero
        heroTitle: 'New Season Collection',
        heroSubtitle: 'Up to 50% off! Start shopping for pieces that reflect your style.',
        heroCta: 'Start Shopping',
        heroCtaSecondary: 'Collections',
        // Shop
        shopTitle: 'Shop',
        shopSubtitle: 'Explore all products',
        filterBy: 'Filter',
        sortBy: 'Sort',
        priceRange: 'Price Range',
        color: 'Color',
        size: 'Size',
        addToCart: 'Add to Cart',
        addToWishlist: 'Add to Wishlist',
        outOfStock: 'Out of Stock',
        inStock: 'In Stock',
        // Categories
        categoriesTitle: 'Categories',
        categoryWomen: 'Women',
        categoryMen: 'Men',
        categoryKids: 'Kids',
        categoryAccessories: 'Accessories',
        // Featured
        newArrivalsTitle: 'New Arrivals',
        bestSellersTitle: 'Best Sellers',
        saleTitle: 'Sale',
        featuredProducts: 'Featured Products',
        viewAll: 'View All',
        // About
        aboutTitle: 'About Us',
        aboutText: 'We have been serving you with fashion passion since 2018.',
        aboutPageTitle: 'About Us',
        ourStory: 'Our Story',
        ourMission: 'Our Mission',
        ourVision: 'Our Vision',
        // Contact
        contactTitle: 'Contact',
        contactPageTitle: 'Contact',
        contactName: 'Full Name',
        contactEmail: 'Email',
        contactPhone: 'Phone',
        contactMessage: 'Your Message',
        contactSubmit: 'Submit',
        contactAddress: 'Address',
        // Cart
        cartTitle: 'Cart',
        cartEmpty: 'Your cart is empty',
        cartSubtotal: 'Subtotal',
        cartShipping: 'Shipping',
        cartTotal: 'Total',
        cartCheckout: 'Checkout',
        continueShopping: 'Continue Shopping',
        // Wishlist
        wishlistTitle: 'Wishlist',
        wishlistEmpty: 'Your wishlist is empty',
        // Account
        accountTitle: 'My Account',
        ordersTitle: 'My Orders',
        orderHistory: 'Order History',
        accountDetails: 'Account Details',
        addresses: 'My Addresses',
        logout: 'Logout',
        // Footer
        footer: {
            description: 'Serving you with fashion passion.',
            quickLinks: 'Quick Links',
            customerService: 'Customer Service',
            contact: 'Contact',
            home: 'Home',
            shop: 'Shop',
            about: 'About Us',
            faq: 'FAQ',
            shipping: 'Shipping Info',
            returns: 'Returns & Exchanges',
            sizeGuide: 'Size Guide',
            copyright: '© 2026 ShopStyle. All rights reserved.',
            privacyPolicy: 'Privacy Policy',
            termsOfUse: 'Terms of Use',
            paymentMethods: 'Payment Methods',
        },
    },
    de: {
        siteName: 'ShopStyle',
        siteSlogan: 'Entdecken Sie Ihren Stil',
        // Navbar
        nav: {
            home: 'Startseite',
            shop: 'Shop',
            categories: 'Kategorien',
            about: 'Über uns',
            contact: 'Kontakt',
            cart: 'Warenkorb',
            wishlist: 'Wunschliste',
            account: 'Konto',
            women: 'Damen',
            men: 'Herren',
            kids: 'Kinder',
            accessories: 'Accessoires',
            sale: 'Sale',
        },
        // Hero
        heroTitle: 'Neue Saisonkollektion',
        heroSubtitle: 'Bis zu 50% Rabatt! Beginnen Sie mit dem Einkaufen von Stücken, die Ihren Stil widerspiegeln.',
        heroCta: 'Jetzt shoppen',
        heroCtaSecondary: 'Kollektionen',
        // Shop
        shopTitle: 'Shop',
        shopSubtitle: 'Alle Produkte entdecken',
        filterBy: 'Filtern',
        sortBy: 'Sortieren',
        priceRange: 'Preisbereich',
        color: 'Farbe',
        size: 'Größe',
        addToCart: 'In den Warenkorb',
        addToWishlist: 'Zur Wunschliste',
        outOfStock: 'Nicht auf Lager',
        inStock: 'Auf Lager',
        // Kategorien
        categoriesTitle: 'Kategorien',
        categoryWomen: 'Damen',
        categoryMen: 'Herren',
        categoryKids: 'Kinder',
        categoryAccessories: 'Accessoires',
        // Empfohlen
        newArrivalsTitle: 'Neuheiten',
        bestSellersTitle: 'Bestseller',
        saleTitle: 'Sale',
        featuredProducts: 'Empfohlene Produkte',
        viewAll: 'Alle anzeigen',
        // Über uns
        aboutTitle: 'Über uns',
        aboutText: 'Wir dienen Ihnen seit 2018 mit Modeleidenschaft.',
        aboutPageTitle: 'Über uns',
        ourStory: 'Unsere Geschichte',
        ourMission: 'Unsere Mission',
        ourVision: 'Unsere Vision',
        // Kontakt
        contactTitle: 'Kontakt',
        contactPageTitle: 'Kontakt',
        contactName: 'Vollständiger Name',
        contactEmail: 'E-Mail',
        contactPhone: 'Telefon',
        contactMessage: 'Ihre Nachricht',
        contactSubmit: 'Absenden',
        contactAddress: 'Adresse',
        // Warenkorb
        cartTitle: 'Warenkorb',
        cartEmpty: 'Ihr Warenkorb ist leer',
        cartSubtotal: 'Zwischensumme',
        cartShipping: 'Versand',
        cartTotal: 'Gesamt',
        cartCheckout: 'Zur Kasse',
        continueShopping: 'Weiter einkaufen',
        // Wunschliste
        wishlistTitle: 'Wunschliste',
        wishlistEmpty: 'Ihre Wunschliste ist leer',
        // Konto
        accountTitle: 'Mein Konto',
        ordersTitle: 'Meine Bestellungen',
        orderHistory: 'Bestellverlauf',
        accountDetails: 'Kontodetails',
        addresses: 'Meine Adressen',
        logout: 'Abmelden',
        // Footer
        footer: {
            description: 'Wir dienen Ihnen mit Modeleidenschaft.',
            quickLinks: 'Schnelllinks',
            customerService: 'Kundenservice',
            contact: 'Kontakt',
            home: 'Startseite',
            shop: 'Shop',
            about: 'Über uns',
            faq: 'FAQ',
            shipping: 'Versandinfo',
            returns: 'Rückgabe & Umtausch',
            sizeGuide: 'Größentabelle',
            copyright: '© 2026 ShopStyle. Alle Rechte vorbehalten.',
            privacyPolicy: 'Datenschutzrichtlinie',
            termsOfUse: 'Nutzungsbedingungen',
            paymentMethods: 'Zahlungsmethoden',
        },
    },
    fr: {
        siteName: 'ShopStyle',
        siteSlogan: 'Découvrez votre style',
        // Navbar
        nav: {
            home: 'Accueil',
            shop: 'Boutique',
            categories: 'Catégories',
            about: 'À propos',
            contact: 'Contact',
            cart: 'Panier',
            wishlist: 'Liste de souhaits',
            account: 'Compte',
            women: 'Femme',
            men: 'Homme',
            kids: 'Enfants',
            accessories: 'Accessoires',
            sale: 'Soldes',
        },
        // Hero
        heroTitle: 'Nouvelle collection de saison',
        heroSubtitle: 'Jusqu\'à 50% de réduction! Commencez à acheter des pièces qui reflètent votre style.',
        heroCta: 'Commencer les achats',
        heroCtaSecondary: 'Collections',
        // Boutique
        shopTitle: 'Boutique',
        shopSubtitle: 'Découvrez tous les produits',
        filterBy: 'Filtrer',
        sortBy: 'Trier',
        priceRange: 'Gamme de prix',
        color: 'Couleur',
        size: 'Taille',
        addToCart: 'Ajouter au panier',
        addToWishlist: 'Ajouter aux souhaits',
        outOfStock: 'Rupture de stock',
        inStock: 'En stock',
        // Catégories
        categoriesTitle: 'Catégories',
        categoryWomen: 'Femme',
        categoryMen: 'Homme',
        categoryKids: 'Enfants',
        categoryAccessories: 'Accessoires',
        // En vedette
        newArrivalsTitle: 'Nouveautés',
        bestSellersTitle: 'Meilleures ventes',
        saleTitle: 'Soldes',
        featuredProducts: 'Produits en vedette',
        viewAll: 'Voir tout',
        // À propos
        aboutTitle: 'À propos de nous',
        aboutText: 'Nous vous servons avec passion pour la mode depuis 2018.',
        aboutPageTitle: 'À propos de nous',
        ourStory: 'Notre histoire',
        ourMission: 'Notre mission',
        ourVision: 'Notre vision',
        // Contact
        contactTitle: 'Contact',
        contactPageTitle: 'Contact',
        contactName: 'Nom complet',
        contactEmail: 'Email',
        contactPhone: 'Téléphone',
        contactMessage: 'Votre message',
        contactSubmit: 'Envoyer',
        contactAddress: 'Adresse',
        // Panier
        cartTitle: 'Panier',
        cartEmpty: 'Votre panier est vide',
        cartSubtotal: 'Sous-total',
        cartShipping: 'Livraison',
        cartTotal: 'Total',
        cartCheckout: 'Passer à la caisse',
        continueShopping: 'Continuer les achats',
        // Liste de souhaits
        wishlistTitle: 'Liste de souhaits',
        wishlistEmpty: 'Votre liste de souhaits est vide',
        // Compte
        accountTitle: 'Mon compte',
        ordersTitle: 'Mes commandes',
        orderHistory: 'Historique des commandes',
        accountDetails: 'Détails du compte',
        addresses: 'Mes adresses',
        logout: 'Déconnexion',
        // Footer
        footer: {
            description: 'Nous vous servons avec passion pour la mode.',
            quickLinks: 'Liens rapides',
            customerService: 'Service client',
            contact: 'Contact',
            home: 'Accueil',
            shop: 'Boutique',
            about: 'À propos',
            faq: 'FAQ',
            shipping: 'Info livraison',
            returns: 'Retours & Échanges',
            sizeGuide: 'Guide des tailles',
            copyright: '© 2026 ShopStyle. Tous droits réservés.',
            privacyPolicy: 'Politique de confidentialité',
            termsOfUse: 'Conditions d\'utilisation',
            paymentMethods: 'Méthodes de paiement',
        },
    },
};

export const eticaretTheme: ThemeData = {
    metadata: {
        id: 'theme-eticaret',
        name: 'Online Mağaza',
        description: 'E-ticaret ve online mağaza siteleri için profesyonel tema - TR/EN destekli',
        version: '1.0.0',
        thumbnail: '/themes/eticaret.png',
        author: 'Page Builder',
        category: 'ecommerce',
        pages: [
            { slug: 'home', title: 'Ana Sayfa', file: 'pages/home.json' },
            { slug: 'shop', title: 'Mağaza', file: 'pages/shop.json' },
            { slug: 'shop/women', title: 'Kadın', file: 'pages/women.json' },
            { slug: 'shop/men', title: 'Erkek', file: 'pages/men.json' },
            { slug: 'shop/kids', title: 'Çocuk', file: 'pages/kids.json' },
            { slug: 'shop/accessories', title: 'Aksesuarlar', file: 'pages/accessories.json' },
            { slug: 'about', title: 'Hakkımızda', file: 'pages/about.json' },
            { slug: 'contact', title: 'İletişim', file: 'pages/contact.json' },
        ],
        settings: {
            primaryColor: '#ec4899',
            secondaryColor: '#0f172a',
            accentColor: '#f472b6',
            fontFamily: "'Inter', sans-serif",
            defaultLanguage: 'tr',
            translations: translations,
            header: eticaretHeader,
            footer: eticaretFooter,
            company: {
                name: 'ShopStyle',
                slogan: 'Tarzını Keşfet',
                logo: '/themes/ecommerce/logo.svg',
            },
            contact: {
                email: 'destek@shopstyle.com',
                phone: '0850 123 45 67',
                address: 'Kadıköy, Moda Cad. No: 50, İstanbul',
                mapUrl: 'https://maps.google.com/?q=40.9876,29.0389',
            },
            social: {
                facebook: 'https://facebook.com/shopstyle',
                instagram: 'https://instagram.com/shopstyle',
                twitter: 'https://twitter.com/shopstyle',
                youtube: 'https://youtube.com/@shopstyle',
            },
            seo: {
                metaTitle: 'ShopStyle | Online Moda Mağazası - Türkiye',
                metaDescription: 'Kadın, erkek, çocuk giyim ve aksesuar. %50\'ye varan indirimler, ücretsiz kargo ve kolay iade.',
                metaKeywords: 'online alışveriş, moda, giyim, aksesuar, indirim, kadın, erkek, çocuk',
                googleAnalyticsId: '',
            },
            animations: {
                enabled: true,
                defaultType: 'fadeIn',
                defaultDuration: 400,
                staggerDelay: 60,
            },
        },
    },
    pages: {
        home: homePage,
        about: aboutPage,
        contact: contactPage,
        shop: shopPage,
        'shop/women': womenPage,
        'shop/men': menPage,
        'shop/kids': kidsPage,
        'shop/accessories': accessoriesPage,
    },
};

export { eticaretTheme as ecommerceTheme };
