// ============================================
// Restoran Teması - Ana Tema Dosyası
// Restoran ve kafe işletmeleri için - TR/EN destekli
// ============================================

import type { ThemeData } from '@/types/theme';
import { restoranHeader } from './header';
import { restoranFooter } from './footer';
import { homePage } from './pages/home';
import { aboutPage } from './pages/about';
import { contactPage } from './pages/contact';
import { menuPage } from './pages/menu';
import { galleryPage } from './pages/gallery';

const translations = {
    tr: {
        siteName: 'Lezzet Mutfağı',
        siteSlogan: 'Unutulmaz Lezzetler',
        // Navbar
        nav: {
            home: 'Ana Sayfa',
            menu: 'Menü',
            about: 'Hakkımızda',
            gallery: 'Galeri',
            contact: 'İletişim',
            reservation: 'Rezervasyon',
            starters: 'Başlangıçlar',
            mains: 'Ana Yemekler',
            desserts: 'Tatlılar',
            drinks: 'İçecekler',
        },
        // Hero
        heroTitle: 'Damağınıza Layık Lezzetler',
        heroSubtitle: 'Geleneksel tatların modern yorumu. Taze malzemeler, ustalık ve sevgi ile hazırlanan yemekler.',
        heroCta: 'Menümüzü İnceleyin',
        heroCtaSecondary: 'Rezervasyon Yap',
        // Menü
        menuTitle: 'Menümüz',
        menuSubtitle: 'Şeflerimizin özel tarifleri',
        categoryStarters: 'Başlangıçlar',
        categoryMains: 'Ana Yemekler',
        categoryDesserts: 'Tatlılar',
        categoryDrinks: 'İçecekler',
        viewFullMenu: 'Tüm Menüyü Görüntüle',
        // Hakkımızda
        aboutTitle: 'Hikayemiz',
        aboutText: '2010 yılından bu yana, geleneksel lezzetleri modern sunumlarla buluşturuyoruz.',
        aboutPageTitle: 'Hakkımızda',
        ourChef: 'Şefimiz',
        ourTeam: 'Ekibimiz',
        ourStory: 'Hikayemiz',
        // Rezervasyon
        reservationTitle: 'Rezervasyon',
        reservationSubtitle: 'Özel anlarınız için masanızı ayırtın',
        reservationName: 'Ad Soyad',
        reservationEmail: 'E-posta',
        reservationPhone: 'Telefon',
        reservationDate: 'Tarih',
        reservationTime: 'Saat',
        reservationGuests: 'Kişi Sayısı',
        reservationNotes: 'Özel Notlar',
        reservationSubmit: 'Rezervasyon Yap',
        // Galeri
        galleryTitle: 'Galeri',
        gallerySubtitle: 'Mekanımız ve lezzetlerimizden kareler',
        // Referanslar
        testimonialsTitle: 'Misafir Yorumları',
        testimonialsSubtitle: 'Lezzetlerimizi tadanlar ne diyor?',
        // İletişim
        contactTitle: 'Bize Ulaşın',
        contactPageTitle: 'İletişim',
        workingHours: 'Çalışma Saatleri',
        location: 'Konum',
        contactName: 'Ad Soyad',
        contactEmail: 'E-posta',
        contactMessage: 'Mesajınız',
        contactSubmit: 'Gönder',
        // Footer
        footer: {
            description: 'Geleneksel lezzetlerin modern yorumu.',
            quickLinks: 'Hızlı Linkler',
            openingHours: 'Çalışma Saatleri',
            contact: 'İletişim',
            home: 'Ana Sayfa',
            menu: 'Menü',
            about: 'Hakkımızda',
            gallery: 'Galeri',
            weekdays: 'Hafta İçi',
            weekends: 'Hafta Sonu',
            copyright: '© 2026 Lezzet Mutfağı. Tüm hakları saklıdır.',
            privacyPolicy: 'Gizlilik Politikası',
            termsOfUse: 'Kullanım Şartları',
        },
    },
    en: {
        siteName: 'Taste Kitchen',
        siteSlogan: 'Unforgettable Flavors',
        // Navbar
        nav: {
            home: 'Home',
            menu: 'Menu',
            about: 'About',
            gallery: 'Gallery',
            contact: 'Contact',
            reservation: 'Reservation',
            starters: 'Starters',
            mains: 'Main Courses',
            desserts: 'Desserts',
            drinks: 'Drinks',
        },
        // Hero
        heroTitle: 'Flavors Worthy of Your Palate',
        heroSubtitle: 'Modern interpretation of traditional tastes. Dishes prepared with fresh ingredients, skill, and love.',
        heroCta: 'View Our Menu',
        heroCtaSecondary: 'Make Reservation',
        // Menu
        menuTitle: 'Our Menu',
        menuSubtitle: 'Special recipes from our chefs',
        categoryStarters: 'Starters',
        categoryMains: 'Main Courses',
        categoryDesserts: 'Desserts',
        categoryDrinks: 'Drinks',
        viewFullMenu: 'View Full Menu',
        // About
        aboutTitle: 'Our Story',
        aboutText: 'Since 2010, we have been combining traditional flavors with modern presentations.',
        aboutPageTitle: 'About Us',
        ourChef: 'Our Chef',
        ourTeam: 'Our Team',
        ourStory: 'Our Story',
        // Reservation
        reservationTitle: 'Reservation',
        reservationSubtitle: 'Book your table for special moments',
        reservationName: 'Full Name',
        reservationEmail: 'Email',
        reservationPhone: 'Phone',
        reservationDate: 'Date',
        reservationTime: 'Time',
        reservationGuests: 'Number of Guests',
        reservationNotes: 'Special Notes',
        reservationSubmit: 'Make Reservation',
        // Gallery
        galleryTitle: 'Gallery',
        gallerySubtitle: 'Shots from our venue and dishes',
        // Testimonials
        testimonialsTitle: 'Guest Reviews',
        testimonialsSubtitle: 'What our guests say about our flavors?',
        // Contact
        contactTitle: 'Contact Us',
        contactPageTitle: 'Contact',
        workingHours: 'Working Hours',
        location: 'Location',
        contactName: 'Full Name',
        contactEmail: 'Email',
        contactMessage: 'Your Message',
        contactSubmit: 'Submit',
        // Footer
        footer: {
            description: 'Modern interpretation of traditional flavors.',
            quickLinks: 'Quick Links',
            openingHours: 'Opening Hours',
            contact: 'Contact',
            home: 'Home',
            menu: 'Menu',
            about: 'About Us',
            gallery: 'Gallery',
            weekdays: 'Weekdays',
            weekends: 'Weekends',
            copyright: '© 2026 Taste Kitchen. All rights reserved.',
            privacyPolicy: 'Privacy Policy',
            termsOfUse: 'Terms of Use',
        },
    },
    de: {
        siteName: 'Geschmacksküche',
        siteSlogan: 'Unvergessliche Aromen',
        // Navbar
        nav: {
            home: 'Startseite',
            menu: 'Speisekarte',
            about: 'Über uns',
            gallery: 'Galerie',
            contact: 'Kontakt',
            reservation: 'Reservierung',
            starters: 'Vorspeisen',
            mains: 'Hauptgerichte',
            desserts: 'Desserts',
            drinks: 'Getränke',
        },
        // Hero
        heroTitle: 'Aromen für Ihren Gaumen',
        heroSubtitle: 'Moderne Interpretation traditioneller Geschmäcker. Gerichte mit frischen Zutaten, Können und Liebe zubereitet.',
        heroCta: 'Unsere Speisekarte',
        heroCtaSecondary: 'Reservierung',
        // Menü
        menuTitle: 'Unsere Speisekarte',
        menuSubtitle: 'Spezialrezepte unserer Köche',
        categoryStarters: 'Vorspeisen',
        categoryMains: 'Hauptgerichte',
        categoryDesserts: 'Desserts',
        categoryDrinks: 'Getränke',
        viewFullMenu: 'Vollständige Speisekarte',
        // Über uns
        aboutTitle: 'Unsere Geschichte',
        aboutText: 'Seit 2010 verbinden wir traditionelle Aromen mit moderner Präsentation.',
        aboutPageTitle: 'Über uns',
        ourChef: 'Unser Küchenchef',
        ourTeam: 'Unser Team',
        ourStory: 'Unsere Geschichte',
        // Reservierung
        reservationTitle: 'Reservierung',
        reservationSubtitle: 'Reservieren Sie Ihren Tisch für besondere Momente',
        reservationName: 'Vollständiger Name',
        reservationEmail: 'E-Mail',
        reservationPhone: 'Telefon',
        reservationDate: 'Datum',
        reservationTime: 'Uhrzeit',
        reservationGuests: 'Anzahl der Gäste',
        reservationNotes: 'Besondere Hinweise',
        reservationSubmit: 'Reservieren',
        // Galerie
        galleryTitle: 'Galerie',
        gallerySubtitle: 'Bilder aus unserem Lokal und von unseren Gerichten',
        // Testimonials
        testimonialsTitle: 'Gästebewertungen',
        testimonialsSubtitle: 'Was sagen unsere Gäste über unsere Aromen?',
        // Kontakt
        contactTitle: 'Kontakt',
        contactPageTitle: 'Kontakt',
        workingHours: 'Öffnungszeiten',
        location: 'Standort',
        contactName: 'Vollständiger Name',
        contactEmail: 'E-Mail',
        contactMessage: 'Ihre Nachricht',
        contactSubmit: 'Absenden',
        // Footer
        footer: {
            description: 'Moderne Interpretation traditioneller Aromen.',
            quickLinks: 'Schnelllinks',
            openingHours: 'Öffnungszeiten',
            contact: 'Kontakt',
            home: 'Startseite',
            menu: 'Speisekarte',
            about: 'Über uns',
            gallery: 'Galerie',
            weekdays: 'Wochentage',
            weekends: 'Wochenende',
            copyright: '© 2026 Geschmacksküche. Alle Rechte vorbehalten.',
            privacyPolicy: 'Datenschutzrichtlinie',
            termsOfUse: 'Nutzungsbedingungen',
        },
    },
    fr: {
        siteName: 'Cuisine Saveur',
        siteSlogan: 'Saveurs inoubliables',
        // Navbar
        nav: {
            home: 'Accueil',
            menu: 'Menu',
            about: 'À propos',
            gallery: 'Galerie',
            contact: 'Contact',
            reservation: 'Réservation',
            starters: 'Entrées',
            mains: 'Plats principaux',
            desserts: 'Desserts',
            drinks: 'Boissons',
        },
        // Hero
        heroTitle: 'Des saveurs dignes de votre palais',
        heroSubtitle: 'Interprétation moderne des goûts traditionnels. Plats préparés avec des ingrédients frais, savoir-faire et amour.',
        heroCta: 'Voir notre menu',
        heroCtaSecondary: 'Réserver',
        // Menu
        menuTitle: 'Notre menu',
        menuSubtitle: 'Recettes spéciales de nos chefs',
        categoryStarters: 'Entrées',
        categoryMains: 'Plats principaux',
        categoryDesserts: 'Desserts',
        categoryDrinks: 'Boissons',
        viewFullMenu: 'Voir le menu complet',
        // À propos
        aboutTitle: 'Notre histoire',
        aboutText: 'Depuis 2010, nous combinons les saveurs traditionnelles avec des présentations modernes.',
        aboutPageTitle: 'À propos de nous',
        ourChef: 'Notre chef',
        ourTeam: 'Notre équipe',
        ourStory: 'Notre histoire',
        // Réservation
        reservationTitle: 'Réservation',
        reservationSubtitle: 'Réservez votre table pour des moments spéciaux',
        reservationName: 'Nom complet',
        reservationEmail: 'Email',
        reservationPhone: 'Téléphone',
        reservationDate: 'Date',
        reservationTime: 'Heure',
        reservationGuests: 'Nombre de personnes',
        reservationNotes: 'Notes spéciales',
        reservationSubmit: 'Réserver',
        // Galerie
        galleryTitle: 'Galerie',
        gallerySubtitle: 'Photos de notre établissement et de nos plats',
        // Témoignages
        testimonialsTitle: 'Avis clients',
        testimonialsSubtitle: 'Que disent nos clients de nos saveurs?',
        // Contact
        contactTitle: 'Contactez-nous',
        contactPageTitle: 'Contact',
        workingHours: 'Heures d\'ouverture',
        location: 'Emplacement',
        contactName: 'Nom complet',
        contactEmail: 'Email',
        contactMessage: 'Votre message',
        contactSubmit: 'Envoyer',
        // Footer
        footer: {
            description: 'Interprétation moderne des saveurs traditionnelles.',
            quickLinks: 'Liens rapides',
            openingHours: 'Heures d\'ouverture',
            contact: 'Contact',
            home: 'Accueil',
            menu: 'Menu',
            about: 'À propos',
            gallery: 'Galerie',
            weekdays: 'En semaine',
            weekends: 'Week-end',
            copyright: '© 2026 Cuisine Saveur. Tous droits réservés.',
            privacyPolicy: 'Politique de confidentialité',
            termsOfUse: 'Conditions d\'utilisation',
        },
    },
};

export const restoranTheme: ThemeData = {
    metadata: {
        id: 'theme-restoran',
        name: 'Restoran & Kafe',
        description: 'Restoran, kafe ve yeme-içme işletmeleri için profesyonel tema - TR/EN destekli',
        version: '1.0.0',
        thumbnail: '/themes/restoran.png',
        author: 'Page Builder',
        category: 'food',
        pages: [
            { slug: 'home', title: 'Ana Sayfa', file: 'pages/home.json' },
            { slug: 'menu', title: 'Menü', file: 'pages/menu.json' },
            { slug: 'about', title: 'Hakkımızda', file: 'pages/about.json' },
            { slug: 'gallery', title: 'Galeri', file: 'pages/gallery.json' },
            { slug: 'contact', title: 'İletişim', file: 'pages/contact.json' },
        ],
        settings: {
            primaryColor: '#d97706',
            secondaryColor: '#1a1a1a',
            accentColor: '#f59e0b',
            fontFamily: "'Playfair Display', serif",
            defaultLanguage: 'tr',
            translations: translations,
            header: restoranHeader,
            footer: restoranFooter,
            company: {
                name: 'Lezzet Mutfağı',
                slogan: 'Unutulmaz Lezzetler',
                logo: '/themes/restaurant/logo.svg',
            },
            contact: {
                email: 'info@lezzetmutfagi.com',
                phone: '+90 212 345 6789',
                address: 'Beyoğlu, İstiklal Cad. No: 123, İstanbul',
                mapUrl: 'https://maps.google.com/?q=41.0340,28.9770',
            },
            social: {
                facebook: 'https://facebook.com/lezzetmutfagi',
                instagram: 'https://instagram.com/lezzetmutfagi',
                twitter: 'https://twitter.com/lezzetmutfagi',
            },
            seo: {
                metaTitle: 'Lezzet Mutfağı | Restoran & Kafe - İstanbul Beyoğlu',
                metaDescription: 'Geleneksel Türk mutfağının modern yorumu. Taze malzemeler, usta şefler. Rezervasyon için hemen arayın!',
                metaKeywords: 'restoran, kafe, türk mutfağı, beyoğlu, istanbul, yemek, rezervasyon',
                googleAnalyticsId: '',
            },
            animations: {
                enabled: true,
                defaultType: 'fadeIn',
                defaultDuration: 600,
                staggerDelay: 100,
            },
        },
    },
    pages: {
        home: homePage,
        about: aboutPage,
        contact: contactPage,
        menu: menuPage,
        gallery: galleryPage,
    },
};

export { restoranTheme as restaurantTheme };
