// ============================================
// Modern İş Teması - Ana Tema Dosyası
// Dinamik ve modern iş web sitesi - TR/EN destekli
// ============================================

import type { ThemeData } from '@/types/theme';
import { homePage } from './pages/home';
import { aboutPage } from './pages/about';
import { contactPage } from './pages/contact';
import { servicesPage } from './pages/services';
import { pricingPage } from './pages/pricing';
import { modernIsHeader } from './header';
import { modernIsFooter } from './footer';

// Çeviriler
const translations = {
  tr: {
    // Site Genel
    siteName: 'Modern İş',
    siteSlogan: 'Geleceğin İş Modeli',
    // Navbar
    nav: {
      home: 'Ana Sayfa',
      services: 'Çözümler',
      pricing: 'Fiyatlandırma',
      about: 'Hakkımızda',
      contact: 'İletişim',
      tryFree: 'Ücretsiz Dene',
      signIn: 'Giriş Yap',
      saas: 'SaaS Platform',
      cloud: 'Bulut Hizmetleri',
      automation: 'Otomasyon',
      analytics: 'Analitik',
    },
    // Hero
    heroTitle: 'Dijital Dünyada Öne Çıkın',
    heroSubtitle: 'Yenilikçi çözümlerle işinizi dijital çağa taşıyoruz. Hız, verimlilik, başarı.',
    heroCta: 'Hemen Başla',
    heroCtaSecondary: 'Demo İzle',
    // Özellikler
    featuresTitle: 'Özellikler',
    featuresSubtitle: 'İşinizi güçlendiren araçlar',
    featureFast: 'Hızlı',
    featureFastDesc: 'Yıldırım hızında performans',
    featureSecure: 'Güvenli',
    featureSecureDesc: 'Kurumsal düzeyde güvenlik',
    featureScalable: 'Ölçeklenebilir',
    featureScalableDesc: 'İşinizle birlikte büyür',
    // Hakkımızda
    aboutTitle: 'Vizyonumuz',
    aboutText: 'İşletmelerin dijital dönüşümüne öncülük ediyoruz.',
    aboutPageTitle: 'Hakkımızda',
    aboutPageDesc: 'Şirketimiz hakkında bilgiler...',
    // İstatistikler
    statsProjects: 'Proje',
    statsClients: 'Müşteri',
    statsCountries: 'Ülke',
    // Referanslar
    testimonialsTitle: 'Müşteri Yorumları',
    testimonialsSubtitle: 'Müşterilerimiz ne diyor?',
    // CTA
    ctaTitle: 'Hazır mısınız?',
    ctaSubtitle: 'Dijital dönüşüme bugün başlayın',
    ctaButton: 'Ücretsiz Deneme',
    // Hizmetler Sayfası
    servicesPageTitle: 'Hizmetlerimiz',
    servicesPageSubtitle: 'Dijital dönüşüm yolculuğunuzda yanınızdayız. İşletmenizi geleceğe taşıyacak kapsamlı çözümler sunuyoruz.',
    serviceDigitalStrategy: 'Dijital Strateji',
    serviceDigitalStrategyDesc: 'İşletmenizin dijital vizyonunu belirliyor, yol haritası oluşturuyoruz.',
    serviceWebDev: 'Web Geliştirme',
    serviceWebDevDesc: 'Modern ve hızlı web uygulamaları geliştiriyoruz.',
    serviceMobile: 'Mobil Uygulama',
    serviceMobileDesc: 'iOS ve Android için native ve cross-platform uygulamalar.',
    serviceCloud: 'Bulut Çözümleri',
    serviceCloudDesc: 'Ölçeklenebilir ve güvenli bulut altyapısı.',
    // Fiyatlandırma Sayfası
    pricingTitle: 'Fiyatlandırma',
    pricingSubtitle: 'İhtiyacınıza uygun plan seçin',
    pricingPageSubtitle: 'Tüm planlarda 14 gün ücretsiz deneme.',
    planStarter: 'Başlangıç',
    planPro: 'Profesyonel',
    planEnterprise: 'Kurumsal',
    planUsers: 'Kullanıcı',
    planStorage: 'Depolama',
    planEmailSupport: 'Email Destek',
    planPhoneSupport: 'Telefon Destek',
    planPrioritySupport: '7/24 Öncelikli Destek',
    planBasicReporting: 'Temel Raporlama',
    planAdvancedReporting: 'Gelişmiş Raporlama',
    planApiAccess: 'API Erişimi',
    planGetStarted: 'Başla',
    planContactUs: 'Bize Ulaşın',
    planMostPopular: 'En Popüler',
    // İletişim Sayfası
    contactPageTitle: 'İletişim',
    contactName: 'Ad Soyad',
    contactEmail: 'E-posta',
    contactMessage: 'Mesaj',
    contactSubmit: 'Gönder',
    // Footer
    footer: {
      description: 'Dijital dönüşümün öncüsü. Yenilikçi çözümlerle işinizi geleceğe taşıyoruz.',
      productLinks: 'Ürünler',
      companyLinks: 'Şirket',
      supportLinks: 'Destek',
      services: 'Hizmetler',
      pricing: 'Fiyatlandırma',
      about: 'Hakkımızda',
      contact: 'İletişim',
      careers: 'Kariyer',
      blog: 'Blog',
      press: 'Basın',
      helpCenter: 'Yardım Merkezi',
      documentation: 'Dokümantasyon',
      apiReference: 'API Referans',
      systemStatus: 'Sistem Durumu',
      newsletterTitle: 'Güncellemelerden Haberdar Olun',
      newsletterSubtitle: 'Yeni özellikler ve ipuçları için kayıt olun.',
      newsletterPlaceholder: 'E-posta adresiniz',
      subscribe: 'Abone Ol',
      copyright: '© 2026 Modern İş. Tüm hakları saklıdır.',
      privacyPolicy: 'Gizlilik Politikası',
      termsOfUse: 'Kullanım Şartları',
      cookiePolicy: 'Çerez Politikası',
      gdpr: 'KVKK',
    },
  },
  en: {
    // Site General
    siteName: 'Modern Business',
    siteSlogan: 'The Business Model of Tomorrow',
    // Navbar
    nav: {
      home: 'Home',
      services: 'Solutions',
      pricing: 'Pricing',
      about: 'About',
      contact: 'Contact',
      tryFree: 'Try Free',
      signIn: 'Sign In',
      saas: 'SaaS Platform',
      cloud: 'Cloud Services',
      automation: 'Automation',
      analytics: 'Analytics',
    },
    // Hero
    heroTitle: 'Stand Out in the Digital World',
    heroSubtitle: 'We bring your business to the digital age with innovative solutions. Speed, efficiency, success.',
    heroCta: 'Get Started',
    heroCtaSecondary: 'Watch Demo',
    // Features
    featuresTitle: 'Features',
    featuresSubtitle: 'Tools that empower your business',
    featureFast: 'Fast',
    featureFastDesc: 'Lightning fast performance',
    featureSecure: 'Secure',
    featureSecureDesc: 'Enterprise-grade security',
    featureScalable: 'Scalable',
    featureScalableDesc: 'Grows with your business',
    // About
    aboutTitle: 'Our Vision',
    aboutText: 'We lead the digital transformation of businesses.',
    aboutPageTitle: 'About Us',
    aboutPageDesc: 'Information about our company...',
    // Stats
    statsProjects: 'Projects',
    statsClients: 'Clients',
    statsCountries: 'Countries',
    // Testimonials
    testimonialsTitle: 'Testimonials',
    testimonialsSubtitle: 'What our clients say?',
    // CTA
    ctaTitle: 'Ready?',
    ctaSubtitle: 'Start your digital transformation today',
    ctaButton: 'Free Trial',
    // Services Page
    servicesPageTitle: 'Our Services',
    servicesPageSubtitle: 'We are with you on your digital transformation journey. We offer comprehensive solutions to take your business to the future.',
    serviceDigitalStrategy: 'Digital Strategy',
    serviceDigitalStrategyDesc: 'We define your business\'s digital vision and create a roadmap.',
    serviceWebDev: 'Web Development',
    serviceWebDevDesc: 'We develop modern and fast web applications.',
    serviceMobile: 'Mobile App',
    serviceMobileDesc: 'Native and cross-platform apps for iOS and Android.',
    serviceCloud: 'Cloud Solutions',
    serviceCloudDesc: 'Scalable and secure cloud infrastructure.',
    // Pricing Page
    pricingTitle: 'Pricing',
    pricingSubtitle: 'Choose the plan that fits your needs',
    pricingPageSubtitle: '14-day free trial on all plans.',
    planStarter: 'Starter',
    planPro: 'Professional',
    planEnterprise: 'Enterprise',
    planUsers: 'Users',
    planStorage: 'Storage',
    planEmailSupport: 'Email Support',
    planPhoneSupport: 'Phone Support',
    planPrioritySupport: '24/7 Priority Support',
    planBasicReporting: 'Basic Reporting',
    planAdvancedReporting: 'Advanced Reporting',
    planApiAccess: 'API Access',
    planGetStarted: 'Get Started',
    planContactUs: 'Contact Us',
    planMostPopular: 'Most Popular',
    // Contact Page
    contactPageTitle: 'Contact',
    contactName: 'Full Name',
    contactEmail: 'Email',
    contactMessage: 'Message',
    contactSubmit: 'Submit',
    // Footer
    footer: {
      description: 'The pioneer of digital transformation. We bring your business to the future with innovative solutions.',
      productLinks: 'Products',
      companyLinks: 'Company',
      supportLinks: 'Support',
      services: 'Services',
      pricing: 'Pricing',
      about: 'About Us',
      contact: 'Contact',
      careers: 'Careers',
      blog: 'Blog',
      press: 'Press',
      helpCenter: 'Help Center',
      documentation: 'Documentation',
      apiReference: 'API Reference',
      systemStatus: 'System Status',
      newsletterTitle: 'Stay Updated',
      newsletterSubtitle: 'Sign up for new features and tips.',
      newsletterPlaceholder: 'Your email address',
      subscribe: 'Subscribe',
      copyright: '© 2026 Modern Business. All rights reserved.',
      privacyPolicy: 'Privacy Policy',
      termsOfUse: 'Terms of Use',
      cookiePolicy: 'Cookie Policy',
      gdpr: 'GDPR',
    },
  },
  de: {
    // Site Allgemein
    siteName: 'Modernes Geschäft',
    siteSlogan: 'Das Geschäftsmodell von Morgen',
    // Navbar
    nav: {
      home: 'Startseite',
      services: 'Lösungen',
      pricing: 'Preise',
      about: 'Über uns',
      contact: 'Kontakt',
      tryFree: 'Kostenlos testen',
      signIn: 'Anmelden',
      saas: 'SaaS-Plattform',
      cloud: 'Cloud-Dienste',
      automation: 'Automatisierung',
      analytics: 'Analytik',
    },
    // Hero
    heroTitle: 'Heben Sie sich in der digitalen Welt ab',
    heroSubtitle: 'Wir bringen Ihr Unternehmen mit innovativen Lösungen ins digitale Zeitalter. Geschwindigkeit, Effizienz, Erfolg.',
    heroCta: 'Jetzt starten',
    heroCtaSecondary: 'Demo ansehen',
    // Funktionen
    featuresTitle: 'Funktionen',
    featuresSubtitle: 'Werkzeuge, die Ihr Unternehmen stärken',
    featureFast: 'Schnell',
    featureFastDesc: 'Blitzschnelle Leistung',
    featureSecure: 'Sicher',
    featureSecureDesc: 'Sicherheit auf Unternehmensniveau',
    featureScalable: 'Skalierbar',
    featureScalableDesc: 'Wächst mit Ihrem Unternehmen',
    // Über uns
    aboutTitle: 'Unsere Vision',
    aboutText: 'Wir führen die digitale Transformation von Unternehmen an.',
    aboutPageTitle: 'Über uns',
    aboutPageDesc: 'Informationen über unser Unternehmen...',
    // Statistiken
    statsProjects: 'Projekte',
    statsClients: 'Kunden',
    statsCountries: 'Länder',
    // Testimonials
    testimonialsTitle: 'Kundenstimmen',
    testimonialsSubtitle: 'Was sagen unsere Kunden?',
    // CTA
    ctaTitle: 'Bereit?',
    ctaSubtitle: 'Starten Sie heute Ihre digitale Transformation',
    ctaButton: 'Kostenlose Testversion',
    // Dienstleistungen Seite
    servicesPageTitle: 'Unsere Dienstleistungen',
    servicesPageSubtitle: 'Wir begleiten Sie auf Ihrer digitalen Transformation. Wir bieten umfassende Lösungen, um Ihr Unternehmen in die Zukunft zu führen.',
    serviceDigitalStrategy: 'Digitale Strategie',
    serviceDigitalStrategyDesc: 'Wir definieren die digitale Vision Ihres Unternehmens und erstellen eine Roadmap.',
    serviceWebDev: 'Webentwicklung',
    serviceWebDevDesc: 'Wir entwickeln moderne und schnelle Webanwendungen.',
    serviceMobile: 'Mobile App',
    serviceMobileDesc: 'Native und plattformübergreifende Apps für iOS und Android.',
    serviceCloud: 'Cloud-Lösungen',
    serviceCloudDesc: 'Skalierbare und sichere Cloud-Infrastruktur.',
    // Preisseite
    pricingTitle: 'Preise',
    pricingSubtitle: 'Wählen Sie den Plan, der zu Ihnen passt',
    pricingPageSubtitle: '14-tägige kostenlose Testversion bei allen Plänen.',
    planStarter: 'Starter',
    planPro: 'Professionell',
    planEnterprise: 'Unternehmen',
    planUsers: 'Benutzer',
    planStorage: 'Speicher',
    planEmailSupport: 'E-Mail-Support',
    planPhoneSupport: 'Telefon-Support',
    planPrioritySupport: '24/7 Prioritäts-Support',
    planBasicReporting: 'Basis-Berichterstattung',
    planAdvancedReporting: 'Erweiterte Berichterstattung',
    planApiAccess: 'API-Zugang',
    planGetStarted: 'Loslegen',
    planContactUs: 'Kontaktieren Sie uns',
    planMostPopular: 'Am beliebtesten',
    // Kontaktseite
    contactPageTitle: 'Kontakt',
    contactName: 'Vollständiger Name',
    contactEmail: 'E-Mail',
    contactMessage: 'Nachricht',
    contactSubmit: 'Absenden',
    // Footer
    footer: {
      description: 'Der Pionier der digitalen Transformation. Wir bringen Ihr Unternehmen mit innovativen Lösungen in die Zukunft.',
      productLinks: 'Produkte',
      companyLinks: 'Unternehmen',
      supportLinks: 'Support',
      services: 'Dienstleistungen',
      pricing: 'Preise',
      about: 'Über uns',
      contact: 'Kontakt',
      careers: 'Karriere',
      blog: 'Blog',
      press: 'Presse',
      helpCenter: 'Hilfezentrum',
      documentation: 'Dokumentation',
      apiReference: 'API-Referenz',
      systemStatus: 'Systemstatus',
      newsletterTitle: 'Bleiben Sie informiert',
      newsletterSubtitle: 'Melden Sie sich für neue Funktionen und Tipps an.',
      newsletterPlaceholder: 'Ihre E-Mail-Adresse',
      subscribe: 'Abonnieren',
      copyright: '© 2026 Modernes Geschäft. Alle Rechte vorbehalten.',
      privacyPolicy: 'Datenschutzrichtlinie',
      termsOfUse: 'Nutzungsbedingungen',
      cookiePolicy: 'Cookie-Richtlinie',
      gdpr: 'DSGVO',
    },
  },
  fr: {
    // Site Général
    siteName: 'Entreprise Moderne',
    siteSlogan: 'Le modèle d\'affaires de demain',
    // Navbar
    nav: {
      home: 'Accueil',
      services: 'Solutions',
      pricing: 'Tarifs',
      about: 'À propos',
      contact: 'Contact',
      tryFree: 'Essai gratuit',
      signIn: 'Connexion',
      saas: 'Plateforme SaaS',
      cloud: 'Services Cloud',
      automation: 'Automatisation',
      analytics: 'Analytique',
    },
    // Hero
    heroTitle: 'Démarquez-vous dans le monde numérique',
    heroSubtitle: 'Nous amenons votre entreprise à l\'ère numérique avec des solutions innovantes. Rapidité, efficacité, succès.',
    heroCta: 'Commencer',
    heroCtaSecondary: 'Voir la démo',
    // Fonctionnalités
    featuresTitle: 'Fonctionnalités',
    featuresSubtitle: 'Des outils qui renforcent votre entreprise',
    featureFast: 'Rapide',
    featureFastDesc: 'Performance ultra-rapide',
    featureSecure: 'Sécurisé',
    featureSecureDesc: 'Sécurité de niveau entreprise',
    featureScalable: 'Évolutif',
    featureScalableDesc: 'Grandit avec votre entreprise',
    // À propos
    aboutTitle: 'Notre Vision',
    aboutText: 'Nous menons la transformation numérique des entreprises.',
    aboutPageTitle: 'À propos de nous',
    aboutPageDesc: 'Informations sur notre entreprise...',
    // Statistiques
    statsProjects: 'Projets',
    statsClients: 'Clients',
    statsCountries: 'Pays',
    // Témoignages
    testimonialsTitle: 'Témoignages',
    testimonialsSubtitle: 'Que disent nos clients ?',
    // CTA
    ctaTitle: 'Prêt ?',
    ctaSubtitle: 'Commencez votre transformation numérique aujourd\'hui',
    ctaButton: 'Essai gratuit',
    // Page Services
    servicesPageTitle: 'Nos services',
    servicesPageSubtitle: 'Nous vous accompagnons dans votre transformation numérique. Nous proposons des solutions complètes pour amener votre entreprise vers l\'avenir.',
    serviceDigitalStrategy: 'Stratégie digitale',
    serviceDigitalStrategyDesc: 'Nous définissons la vision numérique de votre entreprise et créons une feuille de route.',
    serviceWebDev: 'Développement Web',
    serviceWebDevDesc: 'Nous développons des applications web modernes et rapides.',
    serviceMobile: 'Application Mobile',
    serviceMobileDesc: 'Applications natives et multiplateformes pour iOS et Android.',
    serviceCloud: 'Solutions Cloud',
    serviceCloudDesc: 'Infrastructure cloud évolutive et sécurisée.',
    // Page Tarifs
    pricingTitle: 'Tarifs',
    pricingSubtitle: 'Choisissez le plan qui vous convient',
    pricingPageSubtitle: 'Essai gratuit de 14 jours sur tous les plans.',
    planStarter: 'Débutant',
    planPro: 'Professionnel',
    planEnterprise: 'Entreprise',
    planUsers: 'Utilisateurs',
    planStorage: 'Stockage',
    planEmailSupport: 'Support email',
    planPhoneSupport: 'Support téléphonique',
    planPrioritySupport: 'Support prioritaire 24/7',
    planBasicReporting: 'Rapports de base',
    planAdvancedReporting: 'Rapports avancés',
    planApiAccess: 'Accès API',
    planGetStarted: 'Commencer',
    planContactUs: 'Contactez-nous',
    planMostPopular: 'Le plus populaire',
    // Page Contact
    contactPageTitle: 'Contact',
    contactName: 'Nom complet',
    contactEmail: 'Email',
    contactMessage: 'Message',
    contactSubmit: 'Envoyer',
    // Footer
    footer: {
      description: 'Le pionnier de la transformation numérique. Nous amenons votre entreprise vers l\'avenir avec des solutions innovantes.',
      productLinks: 'Produits',
      companyLinks: 'Entreprise',
      supportLinks: 'Support',
      services: 'Services',
      pricing: 'Tarifs',
      about: 'À propos',
      contact: 'Contact',
      careers: 'Carrières',
      blog: 'Blog',
      press: 'Presse',
      helpCenter: 'Centre d\'aide',
      documentation: 'Documentation',
      apiReference: 'Référence API',
      systemStatus: 'État du système',
      newsletterTitle: 'Restez informé',
      newsletterSubtitle: 'Inscrivez-vous pour les nouvelles fonctionnalités et conseils.',
      newsletterPlaceholder: 'Votre adresse email',
      subscribe: 'S\'abonner',
      copyright: '© 2026 Entreprise Moderne. Tous droits réservés.',
      privacyPolicy: 'Politique de confidentialité',
      termsOfUse: 'Conditions d\'utilisation',
      cookiePolicy: 'Politique de cookies',
      gdpr: 'RGPD',
    },
  },
};

export const modernBusinessTheme: ThemeData = {
  metadata: {
    id: 'theme-modern-is',
    name: 'Modern İş',
    description: 'Dinamik ve modern iş web sitesi teması - TR/EN destekli',
    version: '2.0.0',
    thumbnail: '/themes/modern-business.png',
    author: 'Page Builder',
    category: 'business',
    pages: [
      { slug: 'home', title: 'Ana Sayfa', file: 'pages/home.json' },
      { slug: 'about', title: 'Hakkımızda', file: 'pages/about.json' },
      { slug: 'services', title: 'Hizmetler', file: 'pages/services.json' },
      { slug: 'pricing', title: 'Fiyatlandırma', file: 'pages/pricing.json' },
      { slug: 'contact', title: 'İletişim', file: 'pages/contact.json' },
    ],
    settings: {
      primaryColor: '#6366f1', // Indigo
      secondaryColor: '#8b5cf6', // Violet
      accentColor: '#ec4899', // Pink
      fontFamily: "'Inter', sans-serif",
      defaultLanguage: 'tr',
      translations: translations,
      header: modernIsHeader,
      footer: modernIsFooter,
      company: {
        name: 'Modern İş',
        slogan: 'Geleceğin İş Modeli',
        logo: '/themes/modern-business/logo.svg',
      },
      contact: {
        email: 'info@modernis.com',
        phone: '+90 216 789 0123',
        address: 'Maslak, İstanbul',
        mapUrl: 'https://maps.google.com/?q=41.1086,29.0205',
      },
      social: {
        facebook: 'https://facebook.com/modernis',
        instagram: 'https://instagram.com/modernis',
        twitter: 'https://twitter.com/modernis',
        linkedin: 'https://linkedin.com/company/modernis',
        youtube: 'https://youtube.com/@modernis',
      },
      seo: {
        metaTitle: 'Modern İş | Dijital Dönüşüm Çözümleri',
        metaDescription: 'Yenilikçi dijital çözümlerle işinizi geleceğe taşıyın. SaaS, bulut ve otomasyon hizmetleri.',
        metaKeywords: 'dijital dönüşüm, SaaS, bulut, otomasyon, iş çözümleri',
        googleAnalyticsId: '',
      },
      animations: {
        enabled: true,
        defaultType: 'slideUp',
        defaultDuration: 500,
        staggerDelay: 100,
      },
      // Gradient tema özelliği
      gradients: {
        hero: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        cta: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        card: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
      },
    },
  },
  pages: {
    home: homePage,
    about: aboutPage,
    services: servicesPage,
    pricing: pricingPage,
    contact: contactPage,
  },
};

// Export alias
export { modernBusinessTheme as modernIsTheme };
